NAME: 'pretraining_snemi3d'

MODEL:
  pre_train: False
  model_type: 'superhuman'
  input_nc: 1
  output_nc: 1
  if_sigmoid: True
  init_mode_mala: 'kaiming'
  if_skip: 'False'
  filters:
    - 28
    - 36
    - 48
    - 64
    - 80
  upsample_mode: 'transposeS'
  decode_ratio: 1
  merge_mode: 'cat'
  pad_mode: 'zero'
  bn_mode: 'async'
  relu_mode: 'elu'
  init_mode: 'kaiming_normal'
  pretrain_path: '/***/***'

TRAIN:
  resume: False
  if_valid: True
  cache_path: './caches/'
  save_path: './models/'
  pad: 0
  loss_func: 'BCELoss'
  opt_type: 'adam'
  display_freq: 100
  total_iters: 200000
  warmup_iters: 0
  base_lr: 0.01
  end_lr: 0.0001
  save_freq: 2000
  valid_freq: 2000
  decay_iters: 100000
  weight_decay: ~
  power: 1.5
  batch_size: 8
  num_workers: 32
  if_cuda: True
  random_seed: 666
  min_valid_iter: 6000

DATA:
  dataset_name: 'ac3_ac4'
  min_noise_std: 0.01
  max_noise_std: 0.2
  min_kernel_size: 3
  max_kernel_size: 9
  min_sigma: 0
  max_sigma: 2
  data_folder:  '/***/***'


